{
  "comments": [
    {
      "key": {
        "uuid": "1a494da4_3dbbe2c5",
        "filename": "functest_kubernetes/k8stest.py",
        "patchSetId": 3
      },
      "lineNbr": 111,
      "author": {
        "id": 3405
      },
      "writtenOn": "2018-05-21T09:53:15Z",
      "side": 1,
      "message": "logger.exception already prints backtrace",
      "revId": "ea566c26b94b193f3e06a4f0248efa0cefa7d32d",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}